### ISSUE TITLE
create an http 500 page

### ISSUE THREAD

**Issue by willkg** [mozilla/user-advocacy#5]
Instead of the standard Internet Server Error page which is ugly and makes it seem like something horrible has happened, it'd be nice to have a nicer page that's less ugly and still points out something horrible has happened, but that top people are working on it.

Pretty sure this is straight-forward to do in Flask. I'll look into it later tonight or tomorrow.

**Comment by willkg** [comment]
We should do the same with the http 404 page if we haven't, too.

**Comment by willkg** [comment]
Mmm... the 404 page isn't exciting, but it's not bad.

https://useradvocacy.mozilla.org/omg

**Comment by willkg** [comment]
So I'm puzzled--this looks like an http 500 template:

https://github.com/mozilla/user-advocacy/blob/master/flask/useradvocacy/templates/500.html

Is that what people are seeing?

**Comment by chengwang** [comment]
Yes, only if the server is dying (as in the Flask process goes horribly wrong) then it can't return the 500 page. But generally, you should be getting a 500 page if you do something bad. The issue is some of the endpoints are API endpoints that expect JSON and those don't handle html.

**Comment by willkg** [comment]
Ok. Given that, then this probably isn't an issue. Closing it out.
